// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ETHSplitter$Type } from "./ETHSplitter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ETHSplitter"]: ETHSplitter$Type;
    ["contracts/ETHSplitter.sol:ETHSplitter"]: ETHSplitter$Type;
  }

  interface ContractTypesMap {
    ["ETHSplitter"]: GetContractReturnType<ETHSplitter$Type["abi"]>;
    ["contracts/ETHSplitter.sol:ETHSplitter"]: GetContractReturnType<ETHSplitter$Type["abi"]>;
  }
}
