/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ETHSplitter } from "./ETHSplitter";
export * as factories from "./factories";
export { ETHSplitter__factory } from "./factories/ETHSplitter__factory";
